Makefile.env:
	@. make.d/scripts/Makefile.env.sh

clean: down
	@. make.d/scripts/clean.sh

build: target_stage=end
build: build_type=unoptimized

config:
	@. make.d/scripts/config.sh

ps:
	@. make.d/scripts/ps.sh

nuke: down_removes_volumes=yes
nuke:
	@. make.d/scripts/down.sh
