# NOTE: This is where the overrides take place.
services:
  ide:
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      - AMD_VULKAN_ICD=RADV
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.json
    group_add:
      - ${RENDER_GROUP_ID:-0}
      - ${VIDEO_GROUP_ID:-0}
    ports:
      - name: inference_server
        target: "${INFERENCE_SERVER_PORT:-8000}"
        host_ip: 0.0.0.0
        protocol: tcp
        published: "${INFERENCE_SERVER_PORT:-8000}"
        mode: host
      - name: rag_server
        target: "${RAG_SERVER_PORT:-8001}"
        host_ip: 0.0.0.0
        protocol: tcp
        published: "${RAG_SERVER_PORT:-8001}"
        mode: host
    post_start:
      - command: chown ${USER_NAME:-root}:${USER_NAME:-root} ${USER_HOME_DIR:-/root}/.ollama
        user: root
    volumes:
      - huggingface_cache:${USER_HOME_DIR}/.cache/huggingface
volumes:
  huggingface_cache:
