# NOTE: This is where the overrides take place.
services:
  ide:
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      - AMD_VULKAN_ICD=RADV
      - OLLAMA_IGPU_ENABLE=1
      - OLLAMA_NUM_GPU=999
      - OLLAMA_PORT=${OLLAMA_PORT:-11434}
      - OLLAMA_SKIP_GPU_VALIDATION=0
      - OLLAMA_VULKAN=1
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.json
    group_add:
      - ${RENDER_GROUP_ID:-0}
      - ${VIDEO_GROUP_ID:-0}
    ports:
      - name: ollama
        target: ${OLLAMA_PORT:-11434}
        host_ip: 0.0.0.0
        protocol: tcp
        published: "${OLLAMA_PORT:-11434}"
        mode: host
    volumes:
      - ollama_data:${USER_HOME_DIR}/.ollama
volumes:
  ollama_data:
