include make/variables.Makefile
include make/targets.Makefile

export

SHELL := /bin/bash

help:
	@. scripts/help.sh

init:
	@. scripts/init.sh

build:
	@. scripts/build.sh

up:
	@. scripts/up.sh

shell:
	@. scripts/shell.sh

down:
	@. scripts/down.sh
